version: '3.8'

services:
  # Serviço para a API
  api:
    build: . # Usa o Dockerfile no diretório atual
    ports:
      - "3000:3000" # Mapeia a porta 3000 do container para a porta 3000 do host
    environment: # Variáveis de ambiente para a conexão com o banco
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=test_db
    depends_on:
      - db # Define dependência para iniciar o banco de dados antes da API

  # Serviço para o banco de dados MySQL
  db:
    image: mysql:8.0 # Usa a imagem do MySQL versão 8.0
    environment: # Configuração do banco
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
    ports:
      - "3306:3306" # Mapeia a porta 3306 do container para a porta 3306 do host
    volumes:
      - mysql-data:/var/lib/mysql # Volume para persistir os dados do banco
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Arquivo SQL inicial

volumes:
  mysql-data: # Volume nomeado para armazenar os dados do banco
